name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4<% if (pnpm) { %>
      - uses: pnpm/action-setup@v4<% } %>
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --frozen-lockfile' : yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Lint
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm run' %> lint
      - name: Run Tests
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm run' %> test

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4<% if (pnpm) { %>
      - uses: pnpm/action-setup@v4
        with:
          version: 8<% } %>
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --no-lockfile' : yarn ? 'yarn install --no-lockfile' : 'npm install --no-package-lock' %>
      - name: Run Tests
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm run' %> test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: 'test'
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-4.12
          - ember-lts-5.4
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v4<% if (pnpm) { %>
      - uses: pnpm/action-setup@v4
        with:
          version: 8<% } %>
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --frozen-lockfile' : yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }} --skip-cleanup
        working-directory: <%= testAppInfo.location %>
